### ISSUE TITLE
Closing leaderboard crashes

### ISSUE THREAD

**Issue by f0lie** [jacksonet00/github-leaderboard#15]
```
django      | Closing leaderboard zxcv
django      | 172.18.0.1 - - [15/Apr/2021 15:57:44] "GET /app/leaderboard/28/close_if_ended HTTP/1.1" 500 -
django      | Traceback (most recent call last):
django      |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
django      |     response = self.get_response(request)
django      |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 130, in get_response
django      |     response = self._middleware_chain(request)
django      |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 49, in inner
django      |     response = response_for_exception(request, exc)
django      |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 103, in response_for_exception
django      |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
django      |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 138, in handle_uncaught_exception
django      |     return debug.technical_500_response(request, *exc_info)
django      |   File "/usr/local/lib/python3.8/site-packages/django_extensions/management/technical_response.py", line 40, in null_technical_500_response
django      |     raise exc_value.with_traceback(tb)
django      |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
django      |     response = get_response(request)
django      |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
django      |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
django      |   File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
django      |     return func(*args, **kwds)
django      |   File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
django      |     return self.dispatch(request, *args, **kwargs)
django      |   File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
django      |     return bound_method(*args, **kwargs)
django      |   File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
django      |     return view_func(request, *args, **kwargs)
django      |   File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
django      |     return handler(request, *args, **kwargs)
django      |   File "/app/github_leaderboard/app/views.py", line 61, in get
django      |     leaderboard.close_if_ended()
django      |   File "/app/github_leaderboard/app/models.py", line 92, in close_if_ended
django      |     self.refresh()  # fetch latest commit data from repo before closing
django      | AttributeError: 'Leaderboard' object has no attribute 'refresh'
```

**Comment by f0lie** [comment]
I removed that piece of code and currently the piece of code doesn't do anything. Look at app's model.py `close_if_ended.py` function.
